### ISSUE TITLE
Rename .templates/my-template-name/__templateName__.yaml isn't working

### ISSUE THREAD

**Issue by tobiashochguertel** [stegano/vscode-template#18]
https://github.com/stegano/vscode-template/blob/932f3d3730355526808844a8246bc87949cc1cdc/assets/template.config.js#L27

Replace Line 27 with:

```
return base.replace(/__templateName__/gm, templateName);
```

then it works.

**Comment by stegano** [comment]
Hi @tobiashochguertel 

Thanks for your reporting
That’s right. I’ll fix it.

Thanks 😀

**Comment by stegano** [comment]
@all-contributors please add @tobiashochguertel  for bug
