### ISSUE TITLE
Should rename files from templated names

### ISSUE THREAD

**Issue by arnogues** [stegano/vscode-template#4]
Your extension is very good, I love it, but it should have the possibility to rename files from templated names

example : 
```text
/react-component
  - __templateNameToPascalCase__.js
  - __templateNameToPascalCase__.scss
  - index.js
```

**Comment by stegano** [comment]
Thank you for using the template extension! :)
It seems to be a really good idea. 
I will update this feature after some review.

**Comment by stegano** [comment]
@all-contributors please add @arnogues for ideas

**Comment by stegano** [comment]
@arnogues  This feature was added in [v1.1.0](https://github.com/stegano/vscode-template/releases/tag/v1.1.0)
You can update the extension from the link below.
- https://marketplace.visualstudio.com/items?itemName=yongwoo.template

> This feature is disabled by default. If you want to enable this feature, please refer to template.config.js and implement the `replaceFileNameFn` function.

Thank you for suggesting a good idea. 👍

**Comment by VinayakDeshpande11** [comment]
@stegano  Can you please explain this _implement the replaceFileNameFn function._? Where should we implement as it is already implemented in [template.config.js](https://github.com/stegano/vscode-template/blob/master/assets/template.config.js). Thanks in advance.

**Comment by stegano** [comment]
@VinayakDeshpande11 
You can change the codes of the _replaceFileNameFn_ in the _template.config.js_ file. 😁

**Comment by VinayakDeshpande11** [comment]
After changing the code, do we have to rebuild the extension? As the code is changing the filename in my case

```
  replaceFileNameFn: (fileName, templateName, utils) => {
    const {path} = utils;
    // @see https://nodejs.org/api/path.html#path_path_parse_path
    const {base} = path.parse(fileName);
    fileName = base.split('.');
    fileName[0] = templateName;
    return fileName.join('.');
  },
```

This is my new function, but it is not taking the new name. Sorry for sounding Noob, I am new to JS and have been recently using extensions.

**Comment by stegano** [comment]
@VinayakDeshpande11 
Thanks for using this extension 🤗
Changes take effect without having to modify and rebuild the _template.config.js_ file.
If the changed _replaceFileNameFn_ setting is not reflected, try restart VSCode 🤔

**Comment by kidrecursive** [comment]
After changing the config, a VSCode restart is required, here's my renaming function that works:

`  replaceFileNameFn: (fileName, templateName, utils) => {
    const { path } = utils;
    // @see https://nodejs.org/api/path.html#path_path_parse_path
    const { base } = path.parse(fileName);
    // You can change the file name
    return base.replace(/__templateName__/gm, templateName);
  },`
